#------------------------------------------------------------------------------
# Integration Tests for Booleans and Nil
#------------------------------------------------------------------------------

assert( typeof( True ) == Bool )
assert( typeof( False ) == Bool )
assert( True == True )
assert( False == False )
assert( False == Nil )
assert( True != False )
assert( True != Nil )
assert( True == 0 )
assert( True == 1 )
assert( True == 'A' )
assert( True == "" )
assert( True == () )
assert( True == [] )
assert( True == $Foo )
assert( False != 0 )
assert( False != 1 )
assert( False != 'A' )
assert( False != "" )
assert( False != () )
assert( False != [] )
assert( False != $Foo )

