#------------------------------------------------------------------------------
# Integration Tests for Numbers
#------------------------------------------------------------------------------

assert( typeof( 345 ) == Num )
assert( 345 == 345 )

assert( typeof( -345 ) == Num )
assert( -345 == -345 )

assert( typeof( 34.5 ) == Num )
assert( 34.5 == 34.5 )

assert( typeof( -34.5 ) == Num )
assert( -34.5 == -34.5 )

assert( typeof( 3.45e2 ) == Num )
assert( 3.45e2 == 345 )

assert( typeof( -3.45e2 ) == Num )
assert( -3.45e2 == -345 )

assert( typeof( 34500e-2 ) == Num )
assert( 34500e-2 == 345 )

assert( typeof( -34500e-2 ) == Num )
assert( -34500e-2 == -345 )

assert( typeof( 0x159 ) == Num )
assert( 0x159 == 345 )


